bike_stores:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1433
      database: BikeStores
      schema: production
      windows_login: True
      trust_cert: True

