version: 2

sources:
  - name: bike_stores
    database: BikeStores
    schema: production
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks

    schema: sales
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores